### ISSUE TITLE
memory leaks problem

### ISSUE THREAD

**Issue by mckeyan** [tcz/PHPTracker#31] opened 2014-12-19 09:15 UTC
Hi,

I faced the memory leaks problem. It shows in log like "Announce process restarts to prevent memory leaks".

Restarted the phptracker service, mysql, apache. But no response.

What is the solution?

**Comment by jaitaiwan** [comment] 2015-05-11 01:02
@mckeyan unless there's some other issue here that I'm not seeing, this is intended behaviour. Take a look at [lib/PHPTracker/Seeder/Server.php](https://github.com/tcz/PHPTracker/blob/a16c202cdfec457fa9d845571c91bf539412f4c7/lib/PHPTracker/Seeder/Server.php) at the announce function. It's designed to by default iterate 20 times before restarting and should sleep for 30 second intervals per iteration.

I'm going to close this issue unless there's some more information that can be provided.

**Closed by jaitaiwan** 2015-05-11 01:02 UTC
Labels: bug, needs clarification
